-- Supabase Database Schema for Royal Oud Fragrances

-- 1. Create the products table
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    price TEXT NOT NULL,
    image TEXT NOT NULL,
    "desc" TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS) on products
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Allow anyone (public) to view the products
CREATE POLICY "Allow public read access to products" ON public.products
    FOR SELECT USING (true);

-- Insert the default perfumes
INSERT INTO public.products (name, category, price, image, "desc") VALUES
('Midnight Oud', 'Men', 'Rs. 4,500', 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?q=80&w=600&h=800&fit=crop', 'Deep, woody and mysterious.'),
('Velvet Rose', 'Women', 'Rs. 3,800', 'https://images.unsplash.com/photo-1594035910387-fea47794261f?q=80&w=600&h=800&fit=crop', 'Elegant floral notes for the modern woman.')
ON CONFLICT DO NOTHING;


-- 2. Create the leads/orders table
CREATE TABLE IF NOT EXISTS public.leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT NOT NULL UNIQUE,
    product_name TEXT NOT NULL,
    price TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS) on leads
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

-- Allow public inserts (so users can place orders from the front-end)
CREATE POLICY "Allow public inserts to leads" ON public.leads
    FOR INSERT WITH CHECK (true);

-- Restrict read access to only database admins (authenticated role/dashboard)
CREATE POLICY "Restrict read access to leads" ON public.leads
    FOR SELECT TO authenticated USING (true);
